# Generated by Django 5.0.8 on 2024-08-22 13:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_site_options_alter_site_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
                ('client_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='Bitrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client_endpoint', models.CharField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_status', models.CharField(max_length=1)),
                ('access_token', models.CharField(blank=True, max_length=255)),
                ('refresh_token', models.CharField(blank=True, max_length=255)),
                ('application_token', models.CharField(blank=True, max_length=255)),
                ('storage_id', models.CharField(blank=True, max_length=255)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='bitrix.app')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='bitrix.bitrix')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(max_length=50)),
                ('app_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bitrix.appinstance')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('expires_at', models.DateTimeField()),
                ('portal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bitrix.bitrix')),
            ],
        ),
    ]
