# Generated by Django 5.0.8 on 2024-08-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='connector',
            field=models.BooleanField(default=False),
        ),
    ]
