# Generated by Django 5.0.8 on 2024-09-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0003_alter_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(blank=True, choices=[('olx', 'olx'), ('waba', 'waba')], max_length=255),
        ),
    ]
